// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_joke from "./routes/api/joke.ts";
import * as $greet_name_ from "./routes/greet/[name].tsx";
import * as $index from "./routes/index.tsx";
import * as $post_id_ from "./routes/post/[id].tsx";
import * as $post_create from "./routes/post/create.tsx";
import * as $search from "./routes/search.tsx";
import * as $Counter from "./islands/Counter.tsx";
import * as $Search from "./islands/Search.tsx";
import * as $ToggleView from "./islands/ToggleView.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/joke.ts": $api_joke,
    "./routes/greet/[name].tsx": $greet_name_,
    "./routes/index.tsx": $index,
    "./routes/post/[id].tsx": $post_id_,
    "./routes/post/create.tsx": $post_create,
    "./routes/search.tsx": $search,
  },
  islands: {
    "./islands/Counter.tsx": $Counter,
    "./islands/Search.tsx": $Search,
    "./islands/ToggleView.tsx": $ToggleView,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
